//! Fuzz-harness scaffold generation for external engines such as afl.rs and honggfuzz.

use syn::{FnArg, ImplItem, Item, ItemImpl, Pat, ReturnType, Type, Visibility};

/// Supported fuzzing backends that Sanctifier can scaffold.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FuzzHarnessTarget {
    /// Generate an `afl.rs` harness.
    Afl,
    /// Generate a `honggfuzz` harness.
    Honggfuzz,
}

impl FuzzHarnessTarget {
    /// Returns the canonical file name for this scaffold.
    pub fn file_name(self) -> &'static str {
        match self {
            FuzzHarnessTarget::Afl => "afl.rs",
            FuzzHarnessTarget::Honggfuzz => "honggfuzz.rs",
        }
    }

    fn crate_name(self) -> &'static str {
        match self {
            FuzzHarnessTarget::Afl => "afl",
            FuzzHarnessTarget::Honggfuzz => "honggfuzz",
        }
    }
}

/// A discovered public entrypoint that can guide harness authors.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FuzzEntrypoint {
    /// Function name.
    pub name: String,
    /// Human-readable argument list excluding any receiver.
    pub args: Vec<String>,
    /// Human-readable return type.
    pub return_type: String,
}

/// Parsed contract metadata used to render fuzzing scaffolds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FuzzHarnessSpec {
    /// Path to the source file used as the generator input.
    pub source_path: String,
    /// Contract type name when one can be inferred.
    pub contract_name: Option<String>,
    /// Public entrypoints discovered in impl blocks.
    pub entrypoints: Vec<FuzzEntrypoint>,
}

/// Generates Soroban-oriented fuzzing harness scaffolds.
pub struct FuzzHarnessGenerator;

impl FuzzHarnessGenerator {
    /// Parse contract source and collect entrypoint metadata for scaffold rendering.
    pub fn inspect_source(source: &str, source_path: &str) -> FuzzHarnessSpec {
        let parsed = syn::parse_file(source);
        let mut contract_name = None;
        let mut entrypoints = Vec::new();

        if let Ok(file) = parsed {
            contract_name = file
                .items
                .iter()
                .find_map(Self::extract_contract_struct_name);

            for item in &file.items {
                if let Item::Impl(item_impl) = item {
                    entrypoints.extend(Self::extract_entrypoints(item_impl));
                }
            }
        }

        FuzzHarnessSpec {
            source_path: source_path.to_string(),
            contract_name,
            entrypoints,
        }
    }

    /// Render a complete fuzz-harness source file for the chosen backend.
    pub fn render(spec: &FuzzHarnessSpec, target: FuzzHarnessTarget) -> String {
        let backend_comment = match target {
            FuzzHarnessTarget::Afl => "afl.rs",
            FuzzHarnessTarget::Honggfuzz => "honggfuzz",
        };
        let contract_label = spec.contract_name.as_deref().unwrap_or("UnknownContract");
        let entrypoint_lines = if spec.entrypoints.is_empty() {
            vec!["// - No public contract entrypoints were discovered.".to_string()]
        } else {
            spec.entrypoints
                .iter()
                .map(|entrypoint| {
                    format!(
                        "// - {}({}) -> {}",
                        entrypoint.name,
                        entrypoint.args.join(", "),
                        entrypoint.return_type
                    )
                })
                .collect::<Vec<_>>()
        };
        let invocation_stubs = if spec.entrypoints.is_empty() {
            "    // TODO: map the fuzzer input into one or more contract entrypoints.\n".to_string()
        } else {
            spec.entrypoints
                .iter()
                .map(|entrypoint| {
                    format!(
                        "    // TODO: decode `data` into arguments for `{}` and invoke it here.\n",
                        entrypoint.name
                    )
                })
                .collect::<String>()
        };

        format!(
            r#"#![allow(dead_code)]
// Generated by Sanctifier to bridge static analysis into dynamic fuzzing.
// Backend: {backend_comment}
// Source: {source_path}
// Contract: {contract_label}
//
// Discovered public entrypoints:
{entrypoint_lines}
//
// Before running this harness:
// 1. Add `{crate_name}` to the fuzz crate's dependencies.
// 2. Replace the placeholder module path below with your contract crate.
// 3. Decode `data` into Soroban values and drive realistic contract state.

use {crate_name}::fuzz;

#[allow(unused_imports)]
use soroban_sdk::Env;

// TODO: point this import at the contract crate or include the target source directly.
// use your_contract_crate::{contract_label};

fn exercise_target(data: &[u8]) {{
    let _ = data;

{invocation_stubs}    // Example:
    // let _env: Env = todo!("construct a Soroban environment for this harness");
    // let contract = {contract_label};
    // let result = contract.some_entrypoint(_env, /* decoded args */);
    // let _ = result;
}}

fn main() {{
    fuzz!(|data: &[u8]| {{
        exercise_target(data);
    }});
}}
"#,
            backend_comment = backend_comment,
            source_path = spec.source_path,
            contract_label = contract_label,
            entrypoint_lines = entrypoint_lines.join("\n"),
            crate_name = target.crate_name(),
            invocation_stubs = invocation_stubs,
        )
    }

    fn extract_contract_struct_name(item: &Item) -> Option<String> {
        let item_struct = match item {
            Item::Struct(item_struct) => item_struct,
            _ => return None,
        };

        if Self::has_attribute(&item_struct.attrs, "contract") {
            Some(item_struct.ident.to_string())
        } else {
            None
        }
    }

    fn extract_entrypoints(item_impl: &ItemImpl) -> Vec<FuzzEntrypoint> {
        item_impl
            .items
            .iter()
            .filter_map(|item| match item {
                ImplItem::Fn(function) if matches!(function.vis, Visibility::Public(_)) => {
                    let args = function
                        .sig
                        .inputs
                        .iter()
                        .filter_map(|arg| match arg {
                            FnArg::Receiver(_) => None,
                            FnArg::Typed(typed) => {
                                let name = match typed.pat.as_ref() {
                                    Pat::Ident(ident) => ident.ident.to_string(),
                                    _ => "_".to_string(),
                                };
                                let ty = Self::type_to_string(typed.ty.as_ref());
                                Some(format!("{}: {}", name, ty))
                            }
                        })
                        .collect::<Vec<_>>();
                    let return_type = match &function.sig.output {
                        ReturnType::Default => "()".to_string(),
                        ReturnType::Type(_, ty) => Self::type_to_string(ty.as_ref()),
                    };
                    Some(FuzzEntrypoint {
                        name: function.sig.ident.to_string(),
                        args,
                        return_type,
                    })
                }
                _ => None,
            })
            .collect()
    }

    fn type_to_string(ty: &Type) -> String {
        let tokens = quote::quote!(#ty).to_string();
        tokens
            .replace(" < ", "<")
            .replace(" >", ">")
            .replace(" ,", ",")
    }

    fn has_attribute(attrs: &[syn::Attribute], name: &str) -> bool {
        attrs.iter().any(|attr| attr.path().is_ident(name))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn inspect_source_collects_public_entrypoints() {
        let source = r#"
            use soroban_sdk::{contract, contractimpl, Address, Env};

            #[contract]
            pub struct Vault;

            #[contractimpl]
            impl Vault {
                pub fn deposit(env: Env, user: Address, amount: i128) -> Result<(), u32> {
                    Ok(())
                }

                fn helper(env: Env) {}
            }
        "#;

        let spec = FuzzHarnessGenerator::inspect_source(source, "src/lib.rs");
        assert_eq!(spec.contract_name.as_deref(), Some("Vault"));
        assert_eq!(spec.entrypoints.len(), 1);
        assert_eq!(spec.entrypoints[0].name, "deposit");
        assert_eq!(spec.entrypoints[0].args[0], "env: Env");
        assert_eq!(spec.entrypoints[0].return_type, "Result<(), u32>");
    }

    #[test]
    fn render_mentions_backend_and_entrypoints() {
        let spec = FuzzHarnessSpec {
            source_path: "src/lib.rs".to_string(),
            contract_name: Some("Vault".to_string()),
            entrypoints: vec![FuzzEntrypoint {
                name: "deposit".to_string(),
                args: vec!["env: Env".to_string(), "amount: i128".to_string()],
                return_type: "()".to_string(),
            }],
        };

        let rendered = FuzzHarnessGenerator::render(&spec, FuzzHarnessTarget::Honggfuzz);
        assert!(rendered.contains("Backend: honggfuzz"));
        assert!(rendered.contains("deposit(env: Env, amount: i128) -> ()"));
        assert!(rendered.contains("use honggfuzz::fuzz;"));
    }
}
